# Use the README file as a reference to customize settings.

Post:
  fields:
    default: title, description, imageUrl, date_posted
    form: title, description, imageUrl, date_posted
  relationships: 
  application: Application
