# Use the README file as a reference to customize settings.

User:
  fields:
    default: email, name, surname, password, dob, tel, country, state, city, zip, address
    form: email, name, surname, password, dob, tel, country, state, city, zip, address
  relationships: 
  application: Application
